### PR TITLE
fix: App service staging slot name is too long

### PR DESCRIPTION
**Pull request by christian-calabrese**
### List of changes

Set app service staging slot name to "staging"

### Motivation and context
The slot staging name is automatically concatenated to the name of the app service, therefore it is not necessary to do it via terraform to prevent extremely long names

### Type of changes

- [ ] Add new resources
- [X] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [X] No

### CODE REVIEW

**Comment by gunzip** [comment]
isn't this a breaking chage for all of those who already use the old name? I mean in case, they're pointing to main

**Review by Krusty93 — APPROVED** [review]

**Comment by gunzip** [comment]
is it possible that the deploy pipeline points to the old name?

**Comment by christian-calabrese** [comment]
> isn't this a breaking chage for all of those who already use the old name? I mean in case, they're pointing to main

Yes, it is, but luckily nobody is using the module with the slot enabled yet. The only project is io-services-cms, which developers suggested the fix

**Comment by Krusty93** [comment]
> > isn't this a breaking chage for all of those who already use the old name? I mean in case, they're pointing to main
> 
> Yes, it is, but luckily nobody is using the module with the slot enabled yet. The only project is io-services-cms, which developers suggested the fix

Exactly, only reference found is https://github.com/pagopa/io-services-cms/blob/1e19669026c7014f82df3a57b1d60b01d544d569/infra/_modules/backoffice/main.tf#L6

**Comment by christian-calabrese** [comment]
> is it possible that the deploy pipeline points to the old name?

In the module from terraform-azurerm-v3, the name of the slot is chosen by the user, so it shouldn't be an issue

**Pull request merged**
